# Generated by Django 4.0.1 on 2022-01-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('actuation_distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bottom_distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('operating_force', models.IntegerField()),
                ('bottom_force', models.IntegerField()),
                ('mount', models.CharField(max_length=50)),
            ],
        ),
    ]
