# Generated by Django 4.0.1 on 2022-01-15 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_switch_options_switch_image_switch_img_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='switch',
            old_name='img_source',
            new_name='image_source',
        ),
    ]
