# Generated by Django 4.0.1 on 2022-01-20 00:03

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_switch_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='image',
            field=models.FileField(null=True, upload_to=api.models.logo_dir_path),
        ),
    ]
