# Generated by Django 4.0.1 on 2022-01-20 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_switch_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='image_url',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
