# Generated by Django 4.0.1 on 2022-01-20 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_switch_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='switch',
            old_name='image_url',
            new_name='image_source_url',
        ),
    ]
