# Generated by Django 4.0.1 on 2022-01-25 04:12

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_image_url_switch_image_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='brand_image',
            field=models.FileField(null=True, upload_to=api.models.logo_dir_path_icon),
        ),
    ]
