# Generated by Django 4.0.1 on 2022-01-25 04:21

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_switch_brand_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='brand_image',
            field=models.FileField(blank=True, null=True, upload_to=api.models.logo_dir_path_icon),
        ),
    ]
