# Generated by Django 4.0.1 on 2022-01-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_switch_brand_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='image_source_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
