# Generated by Django 4.0.1 on 2022-01-25 05:04

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_switch_image_source_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to=api.models.logo_dir_path)),
            ],
        ),
        migrations.RemoveField(
            model_name='switch',
            name='brand_image',
        ),
        migrations.AlterField(
            model_name='switch',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.brand'),
        ),
    ]
