# Generated by Django 4.0.1 on 2022-01-25 05:25

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_brand_remove_switch_brand_image_alter_switch_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=api.models.logo_dir_path_icon),
        ),
    ]
