# Generated by Django 4.1 on 2022-11-11 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_brand_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='bottom_force',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='switch',
            name='operating_force',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
